Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # Day 3 - Operators
... 
... a, b = 10, 3
... 
... print(a + b, a - b, a * b, a / b, a // b, a % b, a ** b)
... 
... a += 5
... print(a > b, a == b, a != b)
... 
... skills = ["Python", "Java", "AI"]
... print("Python" in skills)
... 
... x = [1, 2]
... y = x
... print(x is y)
... 
... print(True and False, True or False, not True)
... 
... print(5 & 2, 5 | 2, 5 ^ 2, 5 << 1, 5 >> 1)
... 
... name = input("Enter your name: ")
